export default {
  status: 'founded',
  msg: 'find something',
  number: 4,
  result: [
    {
      name: 'Soft Oatmeal Cookies',
      description: 'These oatmeal cookies are perfectly flavored and lightly spiced with just a touch of cinnamon. They`re soft, chewy, and easily customizable — just add 1 cup raisins, nuts, or chocolate chips when you mix in the oats. Keep them on hand for after-school snacking or make a batch for a holiday cookie exchange.  ',
      category: 'Dessert',
      materials: [
        '2 cups all-purpose flour ',
        '1 ½ teaspoons ground cinnamon ',
        '1 teaspoon baking soda  ',
        '1 teaspoon salt  ',
        '1 cup unsalted butter, softened ',
        '1 cup white sugar  ',
        '1 cup packed brown sugar ',
        '2 large eggs ',
        '1 teaspoon vanilla extract ',
        '3 cups quick cooking oats ',
        'nonstick cooking spray with flour ',
        '2 tablespoons water ',
        '2 tablespoons white sugar, or as needed ',
      ],
      steps: [
        'Whisk flour, cinnamon, baking soda, and salt together in a medium bowl until well combined..',
        'Beat butter, 1 cup white sugar, and brown sugar in a large bowl with an electric mixer until creamy, at least 2 to 3 minutes. Beat in eggs, one at a time, then mix in vanilla. Gradually mix in dry ingredients until well combined. Add oats and mix until thoroughly incorporated. Cover the bowl and chill dough in the refrigerator for at least 1 hour.',
        'When ready to bake, preheat the oven to 375 degrees F (190 degrees C). Spray two cookie sheets with floured cooking spray. Place water in a small bowl and 2 tablespoons sugar in another small bowl.',
        'Roll chilled dough into walnut-sized balls, and place 2 inches apart on the prepared cookie sheets. Dip a large fork in water, then in sugar, and use to flatten each cookie, rewetting and resugaring as necessary.',
        'Bake in the preheated oven until light golden brown around the edges and centers are nearly set, 8 to 10 minutes, switching racks halfway through. Allow cookies to cool on baking sheet for 5 minutes before transferring to a wire rack to cool completely.',
      ],
      tips: [
        'Per Serving: 218 calories; protein 3g; carbohydrates 32.3g; fat 8.8g; cholesterol 35.8mg; sodium 213.1mg.',
      ],
      recipeId: '#3',
      imgUrl: 'https://user-images.githubusercontent.com/78824988/188838110-1dc4e3d2-42c1-40d6-9e59-0b7ac3664cb0.jpeg',
      metaData: {
        prep: '15Min',
        cook: '10Min',
        additional: '1Hr5Min',
        servings: '24',
      },
      difficulty: 'intermediate',
      publisher: 'Reciper',
    },
    {
      name: 'Chocolate Truffle Cookies',
      description: 'A very dark, rich chocolate cookie for the true chocoholic. This recipe uses relatively little flour, resulting in dense, fudge-like cookies. These cookies keep well in the freezer (but you may have a hard time waiting for them to thaw before you eat them). ',
      category: 'Dessert',
      materials: [
        '4 (1 ounce) squares unsweetened chocolate, chopped ',
        '1 cup semisweet chocolate chips ',
        '6 tablespoons butter ',
        '3 eggs ',
        '1 cup white sugar ',
        '1 ½ teaspoons vanilla extract ',
        '½ cup all-purpose flour ',
        '2 tablespoons unsweetened cocoa powder ',
        '¼ teaspoon baking powder ',
        '¼ teaspoon salt ',
        '1 cup semisweet chocolate chips ',
      ],
      steps: [
        'In the microwave or in a metal bowl over a pan of simmering water, melt unsweetened chocolate, 1 cup of the chocolate chips, and the butter stirring occasionally until smooth. Remove from heat and set aside to cool. In a large bowl, whip eggs and sugar until thick and pale, about 2 minutes. Stir in the vanilla and the chocolate mixture until well mixed. Combine the flour, cocoa, baking powder and salt; gradually stir into the chocolate mixture. Fold in remaining 1 cup chocolate chips. Cover dough and chill for at least an hour or overnight.',
        'Preheat oven to 350 degrees F (175 degrees C). Roll chilled dough into 1 inch balls. Place on ungreased cookie sheets so they are 2 inches apart.',
        'Bake for 9 to 11 minutes in the preheated oven. Allow cookies to cool on baking sheet for 5 minutes before removing to a wire rack to cool completely.',
      ],
      tips: [
        'Per Serving:  112 calories; protein 1.6g; carbohydrates 13.9g; fat 6.8g; cholesterol 20.6mg; sodium 40mg. ',
      ],
      imgUrl: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F442366.jpg',
      metaData: {
        prep: '15 mins ',
        cook: '10 mins ',
        additional: '1 hr 35 mins ',
        servings: '36 ',
        total: '2 hrs ',
        yield: '3 dozen ',
      },
      recipeId: '#8',
      difficulty: 'intermediate',
      publisher: 'Reciper',
    },
    {
      name: 'Chocolate Oatmeal Cookies',
      description: 'These chocolate oatmeal cookies are packed with energizing ingredients and please even a finicky teenager! ',
      category: 'Dessert',
      materials: [
        '1 cup all-purpose flour ',
        '3 tablespoons unsweetened cocoa powder ',
        '1 teaspoon baking powder ',
        '½ teaspoon baking soda ',
        '½ teaspoon salt ',
        '½ teaspoon ground cinnamon ',
        '½ cup margarine ',
        '½ cup brown sugar ',
        '½ cup white sugar ',
        '1 large egg ',
        '1 teaspoon vanilla extract ',
        '1 ¼ cups rolled oats ',
        '½ cup semisweet chocolate chips ',
      ],
      steps: [
        'Preheat the oven to 350 degrees F (175 degrees C). Grease cookie sheets.',
        'Stir flour, cocoa, baking powder, baking soda, salt, and cinnamon together in a large bowl; set aside.',
        'Beat margarine, brown sugar, and white sugar together in a large bowl with an electric mixer until light and fluffy. Beat in egg and vanilla. Stir in flour mixture using a wooden spoon. Mix in oats and chocolate chips. Drop spoonfuls of dough 2 inches apart onto the prepared cookie sheets.',
        'Bake in the preheated oven until edges are golden, about 8 to 10 minutes. Cool on the baking sheet briefly before removing to a wire rack to cool completely.',
      ],
      tips: [
        'Per Serving:  79 calories; protein 1.1g; carbohydrates 11.1g; fat 3.6g; cholesterol 5.2mg; sodium 92.1mg. ',
      ],
      imgUrl: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F06%2F23%2F377334-chocolate-oatmeal-cookies-TTV78-4x3-1.jpg',
      metaData: {
        prep: '15 mins ',
        cook: '10 mins ',
        additional: '1Hr5Min',
        servings: '36 ',
        total: '25 mins ',
        yield: '3 dozen cookies ',
      },
      recipeId: '#9',
      difficulty: 'intermediate',
      publisher: 'Reciper',
    },
    {
      name: 'Easy Lemon Cookies',
      description: 'Lemon cookies from cake mix with a twist. ',
      category: 'Dessert',
      materials: [
        '1 (15.25 ounce) package lemon cake mix ',
        '2 large eggs ',
        '⅓ cup vegetable oil ',
        '1 teaspoon lemon extract ',
        "⅓ cup confectioners' sugar for decoration ",
      ],
      steps: [
        'Preheat the oven to 375 degrees F (190 degrees C).',
        'Pour cake mix into a large bowl. Stir in eggs, oil, and lemon extract until well blended.',
        "Working in batches, drop teaspoonfuls of dough into a bowl of confectioners' sugar. Roll dough in sugar until lightly coated, then place 2 inches apart onto ungreased cookie sheets.",
        'Bake in the preheated oven until the bottoms are light brown, 6 to 9 minutes.',
      ],
      tips: [
        'Per Serving:  87 calories; protein 1.2g; carbohydrates 11.6g; fat 4g; cholesterol 14mg; sodium 106.7mg. ',
      ],
      imgUrl: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F887122.jpg',
      metaData: {
        prep: '10 mins ',
        cook: '10 mins ',
        additional: '1Hr5Min',
        servings: '36 ',
        total: '20 mins ',
        yield: '36 cookies ',
      },
      recipeId: '#11',
      difficulty: 'intermediate',
      publisher: 'Reciper',
    },
  ],
};
