export default {
  trendRecipes: [
    {
      name: 'Soft Oatmeal Cookies',
      description: 'These oatmeal cookies are perfectly flavored and lightly spiced with just a touch of cinnamon. They`re soft, chewy, and easily customizable — just add 1 cup raisins, nuts, or chocolate chips when you mix in the oats. Keep them on hand for after-school snacking or make a batch for a holiday cookie exchange.  ',
      category: 'Dessert',
      materials: [
        '2 cups all-purpose flour ',
        '1 ½ teaspoons ground cinnamon ',
        '1 teaspoon baking soda  ',
        '1 teaspoon salt  ',
        '1 cup unsalted butter, softened ',
        '1 cup white sugar  ',
        '1 cup packed brown sugar ',
        '2 large eggs ',
        '1 teaspoon vanilla extract ',
        '3 cups quick cooking oats ',
        'nonstick cooking spray with flour ',
        '2 tablespoons water ',
        '2 tablespoons white sugar, or as needed ',
      ],
      steps: [
        'Whisk flour, cinnamon, baking soda, and salt together in a medium bowl until well combined..',
        'Beat butter, 1 cup white sugar, and brown sugar in a large bowl with an electric mixer until creamy, at least 2 to 3 minutes. Beat in eggs, one at a time, then mix in vanilla. Gradually mix in dry ingredients until well combined. Add oats and mix until thoroughly incorporated. Cover the bowl and chill dough in the refrigerator for at least 1 hour.',
        'When ready to bake, preheat the oven to 375 degrees F (190 degrees C). Spray two cookie sheets with floured cooking spray. Place water in a small bowl and 2 tablespoons sugar in another small bowl.',
        'Roll chilled dough into walnut-sized balls, and place 2 inches apart on the prepared cookie sheets. Dip a large fork in water, then in sugar, and use to flatten each cookie, rewetting and resugaring as necessary.',
        'Bake in the preheated oven until light golden brown around the edges and centers are nearly set, 8 to 10 minutes, switching racks halfway through. Allow cookies to cool on baking sheet for 5 minutes before transferring to a wire rack to cool completely.',
      ],
      tips: [
        'Per Serving: 218 calories; protein 3g; carbohydrates 32.3g; fat 8.8g; cholesterol 35.8mg; sodium 213.1mg.',
      ],
      recipeId: '#3',
      imgUrl: 'https://user-images.githubusercontent.com/78824988/188838110-1dc4e3d2-42c1-40d6-9e59-0b7ac3664cb0.jpeg',
      metaData: {
        prep: '15Min',
        cook: '10Min',
        additional: '1Hr5Min',
        servings: '24',
      },
      difficulty: 'intermediate',
      publisher: 'Reciper',
    },
    {
      name: 'Meatballs',
      description: 'I never knew how to make good meatballs until I found this recipe. I normally make mine with just ground beef and they still taste great. I`ve used the combination of pork, beef and veal and they are equally good. Definitely use fresh bread crumbs and freshly grate your cheese instead of using the canned variety...it really does make a difference. ',
      category: 'Beef',
      materials: [
        '1 pound ground beef ',
        '½ pound ground veal ',
        '½ pound ground pork ',
        '2 cloves garlic, minced ',
        '2 eggs ',
        '1 cup freshly grated Romano cheese ',
        '1 ½ tablespoons chopped Italian flat leaf parsley ',
        'salt and ground black pepper to taste ',
        '2 cups stale Italian bread, crumbled ',
        '1 ½ cups lukewarm water ',
        '1 cup olive oil ',
      ],
      steps: [
        'Combine beef, veal, and pork in a large bowl. Add garlic, eggs, cheese, parsley, salt and pepper.',
        'Blend bread crumbs into meat mixture. Slowly add the water 1/2 cup at a time. The mixture should be very moist but still hold its shape if rolled into meatballs. (I usually use about 1 1/4 cups of water). Shape into meatballs.',
        'Heat olive oil in a large skillet. Fry meatballs in batches. When the meatball is very brown and slightly crisp remove from the heat and drain on a paper towel. (If your mixture is too wet, cover the meatballs while they are cooking so that they hold their shape better.)',
      ],
      tips: [
        'Per Serving:613 calories; protein 26.6g; carbohydrates 6.6g; fat 53.2g; cholesterol 148.6mg; sodium 333.1mg',
      ],
      imgUrl: 'https://user-images.githubusercontent.com/78824988/188808161-65a2743b-45a7-4c05-a34b-efb88126725f.jpeg',
      recipeId: '#1',
      metaData: {
        prep: '30Min',
        cook: '20Min',
        servings: '8',
      },
      difficulty: 'intermediate',
      publisher: 'Reciper',
    },
    {
      name: 'Buckeye Balls',
      description: "Buckeye balls are chocolate-covered balls of peanut butter and confectioners' sugar. ",
      category: 'Dessert',
      materials: [
        "4 cups sifted confectioners' sugar ",
        '1 ½ cups creamy peanut butter ',
        '½ cup butter, softened ',
        '1 teaspoon vanilla extract ',
        '6 ounces semi-sweet chocolate chips ',
        '2 tablespoons shortening ',
      ],
      steps: [
        'Line a baking sheet with waxed paper; set aside.',
        "Place confectioners' sugar, peanut butter, softened butter, and vanilla into a large bowl; mix together with your hands to form a smooth stiff dough. Shape into balls using 2 teaspoons of dough for each ball. Place on prepared baking sheet; refrigerate until ready to coat.",
        'Melt shortening and chocolate together in a metal bowl over a pan of lightly simmering water, stirring occasionally, until smooth; remove from heat.',
        'Remove balls from the refrigerator; insert a wooden toothpick into a ball, and dip into melted chocolate. Return to baking sheet, chocolate-side down, and remove toothpick. Repeat with remaining balls. Refrigerate for 30 minutes to set.',
      ],
      tips: [
        'Per Serving:  204 calories; protein 3.7g; carbohydrates 22.8g; fat 12g; cholesterol 8.1mg; sodium 81.2mg. ',
      ],
      imgUrl: 'https://user-images.githubusercontent.com/78824988/188877947-42b9afef-f2e3-45e3-bfd3-3595c41a8433.jpeg',
      metaData: {
        prep: '45 mins ',
        cook: '10 mins ',
        additional: '30 mins ',
        servings: '30 ',
        total: '1 hr 25 mins ',
        yield: '5 dozen ',
      },
      recipeId: '#4',
      difficulty: 'intermediate',
      publisher: 'Reciper',
    },
    {
      name: 'Meatloaf',
      description: 'This is a very easy and no fail recipe for meatloaf. It won`t take long to make at all, and it`s quite good! ',
      category: 'Beef',
      materials: [
        '1 ½ pounds ground beef ',
        '1 egg ',
        '1 onion, chopped ',
        '1 cup milk ',
        '1 cup dried bread crumbs ',
        'salt and pepper to taste ',
        '2 tablespoons brown sugar ',
        '2 tablespoons prepared mustard ',
        '⅓ cup ketchup ',
      ],
      steps: [
        'Preheat oven to 350 degrees F (175 degrees C).',
        'In a large bowl, combine the beef, egg, onion, milk and bread OR cracker crumbs. Season with salt and pepper to taste and place in a lightly greased 9x5-inch loaf pan, or form into a loaf and place in a lightly greased 9x13-inch baking dish.',
        'In a separate small bowl, combine the brown sugar, mustard and ketchup. Mix well and pour over the meatloaf.',
        'Bake at 350 degrees F (175 degrees C) for 1 hour.',
      ],
      tips: [
        'Per Serving: 372 calories; protein 18.2g; carbohydrates 18.5g; fat 24.7g; cholesterol 98mg; sodium 334.6mg.',
      ],
      imgUrl: 'https://user-images.githubusercontent.com/78824988/188809644-6e1e2de7-bff1-43ba-8a4f-fd7fcf9a7a69.jpeg',
      recipeId: '#2',
      metaData: {
        prep: '15Min',
        cook: '1Hr',
        servings: '8',
      },
      difficulty: 'intermediate',
      publisher: 'Reciper',
    },
  ],
  newRecipes: [
    {
      name: 'Bang Bang Chicken',
      description: "This is a wonderful Americanized version of an extremely popular Sichuan Chinese dish. With twice-fried chicken, you get the crispy fried breading you'd expect, and the bang bang sauce drizzle just makes the entire dish spectacular. You'll love this more than any Chinese takeout version. Pay attention to the notes in the directions!! ",
      category: 'Chicken',
      materials: [
        '⅓ cup milk ',
        '1 egg ',
        '1 pound boneless, skinless chicken breasts, cut into 1-inch cubes ',
        '¼ cup potato starch ',
        '¼ cup all-purpose flour ',
        '½ teaspoon salt ',
        '¼ teaspoon ground black pepper ',
        '¼ teaspoon shichimi togarashi (Japanese red pepper condiment) ',
        ' oil for frying ',
        '¼ cup mayonnaise ',
        '2 tablespoons honey ',
        '2 tablespoons sweet chili sauce ',
        '1 teaspoon gochujang (Korean hot pepper paste) ',
      ],
      steps: [
        'Whisk together milk and egg in a bowl until smooth. Add chicken to egg wash and marinate for 15 minutes. Drain.',
        'Combine potato starch, flour, salt, pepper, and ground red pepper in a bowl and transfer into a large resealable bag. Add egg-washed chicken pieces and shake until each piece is completely dredged.',
        'Heat oil in a large skillet to 325 degrees F (165 degrees C).',
        'Add chicken pieces into the oil in batches, about 5 to 8 pieces at a time, so as not to drop the temperature of the oil. Fry for 90 seconds. Remove to a paper-towel lined plate to drain. Fry remaining chicken pieces.',
        'Increase oil temperature to 350 degrees F (175 degrees C). The oil should be continuously boiling at this point. Carefully re-add the first batch of chicken and fry another 90 seconds. Remove to a paper-towel lined plate to drain. Fry and drain the remaining chicken. Transfer chicken to a medium bowl.',
        'Stir mayonnaise, honey, sweet chili sauce, and gochujang together in a small bowl. Toss fried chicken with sauce to coat.',
      ],
      tips: [
        'Per Serving:  404 calories; protein 26.7g; carbohydrates 27.3g; fat 20.8g; cholesterol 112.4mg; sodium 545.9mg. ',
      ],
      imgUrl: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F07%2F26%2F6644307-bang-bang-chicken-Diana71-1x1-1.jpg',
      metaData: {
        prep: '15 mins ',
        cook: '10 mins ',
        additional: '15 mins ',
        servings: '4 ',
        total: '40 mins ',
        yield: '4 servings ',
      },
      recipeId: '#19',
      difficulty: 'intermediate',
      publisher: 'Reciper',
    },
    {
      name: 'Chocolate Oatmeal Cookies',
      description: 'These chocolate oatmeal cookies are packed with energizing ingredients and please even a finicky teenager! ',
      category: 'Dessert',
      materials: [
        '1 cup all-purpose flour ',
        '3 tablespoons unsweetened cocoa powder ',
        '1 teaspoon baking powder ',
        '½ teaspoon baking soda ',
        '½ teaspoon salt ',
        '½ teaspoon ground cinnamon ',
        '½ cup margarine ',
        '½ cup brown sugar ',
        '½ cup white sugar ',
        '1 large egg ',
        '1 teaspoon vanilla extract ',
        '1 ¼ cups rolled oats ',
        '½ cup semisweet chocolate chips ',
      ],
      steps: [
        'Preheat the oven to 350 degrees F (175 degrees C). Grease cookie sheets.',
        'Stir flour, cocoa, baking powder, baking soda, salt, and cinnamon together in a large bowl; set aside.',
        'Beat margarine, brown sugar, and white sugar together in a large bowl with an electric mixer until light and fluffy. Beat in egg and vanilla. Stir in flour mixture using a wooden spoon. Mix in oats and chocolate chips. Drop spoonfuls of dough 2 inches apart onto the prepared cookie sheets.',
        'Bake in the preheated oven until edges are golden, about 8 to 10 minutes. Cool on the baking sheet briefly before removing to a wire rack to cool completely.',
      ],
      tips: [
        'Per Serving:  79 calories; protein 1.1g; carbohydrates 11.1g; fat 3.6g; cholesterol 5.2mg; sodium 92.1mg. ',
      ],
      imgUrl: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F06%2F23%2F377334-chocolate-oatmeal-cookies-TTV78-4x3-1.jpg',
      metaData: {
        prep: '15 mins ',
        cook: '10 mins ',
        additional: '1Hr5Min',
        servings: '36 ',
        total: '25 mins ',
        yield: '3 dozen cookies ',
      },
      recipeId: '#9',
      difficulty: 'intermediate',
      publisher: 'Reciper',
    },
    {
      name: 'Quick Chili',
      description: "Make quick chili with this easy bean chili recipe that can be as mild or spicy as desired. It's even better the next day. ",
      category: 'Beef',
      materials: [
        '2 pounds ground beef ',
        '1 onion, finely diced ',
        '3 cloves garlic, minced ',
        '2 (14.5 ounce) cans diced tomatoes with green chile peppers ',
        '1 (15 ounce) can kidney beans ',
        '1 (15 ounce) can pinto beans ',
        '1 (14.5 ounce) can diced tomatoes ',
        '1 (8 ounce) can tomato sauce ',
        '1 cup water ',
        '2 tablespoons chili powder ',
        '2 tablespoons white sugar ',
        '1 tablespoon hot pepper sauce ',
        '1 tablespoon ground cumin ',
        '1 tablespoon salt ',
        '1 teaspoon ground black pepper ',
      ],
      steps: [
        'Heat a large stockpot over medium-high heat. Cook and stir ground beef in the hot pot until browned and crumbly, 5 to 7 minutes. Drain and discard grease.',
        'Add onion and garlic to beef and cook until onion is translucent, 3 to 4 minutes.',
        'Stir in diced tomatoes with chile peppers, kidney beans, pinto beans, tomatoes, tomato sauce, water, chili powder, sugar, hot pepper sauce, cumin, salt, and pepper. Bring to a boil, reduce heat, and simmer for 30 minutes.',
      ],
      tips: [
        'Per Serving:  489 calories; protein 25.6g; carbohydrates 26.9g; fat 31.3g; cholesterol 96.5mg; sodium 1909.4mg. ',
      ],
      imgUrl: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2020%2F04%2F10%2F870042_quick-chili-i_rock-lobster.jpg',
      metaData: {
        prep: '10 mins ',
        cook: '40 mins ',
        additional: '1Hr5Min',
        servings: '8 ',
        total: '50 mins ',
      },
      recipeId: '#15',
      difficulty: 'intermediate',
      publisher: 'Reciper',
    },
    {
      name: 'Chocolate Truffle Cookies',
      description: 'A very dark, rich chocolate cookie for the true chocoholic. This recipe uses relatively little flour, resulting in dense, fudge-like cookies. These cookies keep well in the freezer (but you may have a hard time waiting for them to thaw before you eat them). ',
      category: 'Dessert',
      materials: [
        '4 (1 ounce) squares unsweetened chocolate, chopped ',
        '1 cup semisweet chocolate chips ',
        '6 tablespoons butter ',
        '3 eggs ',
        '1 cup white sugar ',
        '1 ½ teaspoons vanilla extract ',
        '½ cup all-purpose flour ',
        '2 tablespoons unsweetened cocoa powder ',
        '¼ teaspoon baking powder ',
        '¼ teaspoon salt ',
        '1 cup semisweet chocolate chips ',
      ],
      steps: [
        'In the microwave or in a metal bowl over a pan of simmering water, melt unsweetened chocolate, 1 cup of the chocolate chips, and the butter stirring occasionally until smooth. Remove from heat and set aside to cool. In a large bowl, whip eggs and sugar until thick and pale, about 2 minutes. Stir in the vanilla and the chocolate mixture until well mixed. Combine the flour, cocoa, baking powder and salt; gradually stir into the chocolate mixture. Fold in remaining 1 cup chocolate chips. Cover dough and chill for at least an hour or overnight.',
        'Preheat oven to 350 degrees F (175 degrees C). Roll chilled dough into 1 inch balls. Place on ungreased cookie sheets so they are 2 inches apart.',
        'Bake for 9 to 11 minutes in the preheated oven. Allow cookies to cool on baking sheet for 5 minutes before removing to a wire rack to cool completely.',
      ],
      tips: [
        'Per Serving:  112 calories; protein 1.6g; carbohydrates 13.9g; fat 6.8g; cholesterol 20.6mg; sodium 40mg. ',
      ],
      imgUrl: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F442366.jpg',
      metaData: {
        prep: '15 mins ',
        cook: '10 mins ',
        additional: '1 hr 35 mins ',
        servings: '36 ',
        total: '2 hrs ',
        yield: '3 dozen ',
      },
      recipeId: '#8',
      difficulty: 'intermediate',
      publisher: 'Reciper',
    },
  ],
  userSuggestion: [
    {
      name: 'Best Damn Chili',
      description: 'This is my best chili recipe. After years of adjusting recipes that were either too spicy or too mild, everyone loves this. Even my finance who hates chili. ',
      category: 'Beef',
      materials: [
        '4 tablespoons olive oil ',
        '1 yellow onion, chopped ',
        '1 red bell pepper, chopped ',
        '1 Anaheim chile pepper, chopped ',
        '2 red jalapeno pepper, chopped ',
        '4 garlic cloves, minced ',
        '2 ½ pounds lean ground beef ',
        '¼ cup Worcestershire sauce ',
        '1 pinch garlic powder, or to taste ',
        '2 beef bouillon cubes ',
        '1 (12 fluid ounce) can or bottle light beer (such as Coors®) ',
        '1 (28 ounce) can crushed San Marzano tomatoes ',
        '1 (14.5 ounce) can fire-roasted diced tomatoes ',
        '1 (12 ounce) can tomato paste ',
        '½ cup white wine ',
        '2 tablespoons chili powder ',
        '2 tablespoons ground cumin ',
        '1 tablespoon brown sugar ',
        '1 tablespoon chipotle pepper sauce ',
        '2 ½ teaspoons dried basil ',
        '1 ½ teaspoons smoked paprika ',
        '1 teaspoon salt ',
        '½ teaspoon dried oregano ',
        '½ teaspoon ground black pepper ',
        "2 (16 ounce) cans dark red kidney beans (such as Bush's®) ",
        '1 cup sour cream ',
        '3 tablespoons chopped fresh cilantro ',
        '½ teaspoon ground cumin ',
      ],
      steps: [
        'Heat oil in a large pot over medium heat; cook and stir onion, bell pepper, Anaheim pepper, jalapeno peppers, and garlic in the hot oil until softened.',
        'Meanwhile, heat a large skillet over medium-high heat. Cook and stir beef in the hot skillet until browned and crumbly, 5 to 7 minutes; add Worcestershire sauce and garlic powder. Crumble bouillon cubes over beef and add beer. Continue to cook , scraping any browned bits from the bottom of the skillet, until liquid is hot, about 3 minutes. Stir beef mixture into pepper mixture.',
        'Stir crushed tomatoes, diced tomatoes, tomato paste, and wine to the beef mixture. Season with chili powder, 2 tablespoons cumin, brown sugar, pepper sauce, basil, paprika, salt, oregano, and black pepper. Bring to a boil and reduce heat to medium-low. Cover and simmer until meat and vegetables are very tender and flavors have developed in the chili, about 90 minutes, stirring occasionally.',
        'Mix kidney beans into beef and vegetables. Continue to simmer until beans are hot, about 30 minutes more.',
        'Blend sour cream, cilantro, and remaining 1/2 teaspoon cumin in a food processor until smooth. Serve sour cream mixture with chili.',
      ],
      tips: [
        'Per Serving:  406 calories; protein 25.2g; carbohydrates 27.6g; fat 21.1g; cholesterol 74.4mg; sodium 1014.5mg. ',
      ],
      imgUrl: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F04%2F06%2F233613-Best-Damn-Chili-mfs-242-2.jpg',
      metaData: {
        prep: '30 mins ',
        cook: '2 hrs 15 mins ',
        additional: '1Hr5Min',
        servings: '12 ',
        total: '2 hrs 45 mins ',
        yield: '12 servings ',
      },
      recipeId: '#17',
      difficulty: 'intermediate',
      publisher: 'Reciper',
    },
    {
      name: 'Gingerbread Biscotti',
      description: 'These spicy Italian cookies are the perfect accompaniment for cocoa or coffee during the holiday season! Serve with lemon curd or drizzle with lemon flavored almond bark for a special treat. ',
      category: 'Dessert',
      materials: [
        '⅓ cup vegetable oil ',
        '1 cup white sugar ',
        '3 eggs ',
        '¼ cup molasses ',
        '2 ¼ cups all-purpose flour ',
        '1 cup whole wheat flour ',
        '1 tablespoon baking powder ',
        '1 ½ tablespoons ground ginger ',
        '¾ tablespoon ground cinnamon ',
        '½ tablespoon ground cloves ',
        '¼ teaspoon ground nutmeg ',
      ],
      steps: [
        'Preheat the oven to 375 degrees F (190 degrees C). Grease a cookie sheet.',
        'In a large bowl, mix together oil, sugar, eggs, and molasses. In another bowl, combine flours, baking powder, ginger, cinnamon, cloves, and nutmeg; mix into egg mixture to form a stiff dough.',
        'Divide dough in half, and shape each half into a roll the length of the cookie. Place rolls on cookie sheet, and pat down to flatten the dough to 1/2 inch thickness.',
        'Bake in preheated oven for 25 minutes. Remove from oven, and set aside to cool.',
        'When cool enough to touch, cut into 1/2 inch thick diagonal slices. Place sliced biscotti on cookie sheet, and bake an additional 5 to 7 minutes on each side, or until toasted and crispy.',
      ],
      tips: [
        'Per Serving:  70 calories; protein 1.4g; carbohydrates 12.1g; fat 2g; cholesterol 11.6mg; sodium 26.5mg. ',
      ],
      imgUrl: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F2942870.jpg',
      metaData: {
        prep: '25 mins ',
        cook: '40 mins ',
        additional: '1Hr5Min',
        servings: '48 ',
        total: '1 hr 5 mins ',
        yield: '4 dozen ',
      },
      recipeId: '#6',
      difficulty: 'intermediate',
      publisher: 'Reciper',
    },
    {
      name: 'Breakfast Brownies',
      description: "This is a hearty breakfast brownie, quick to fix, and yummy. My kids loved it! It's also gluten-free and dairy-free. ",
      category: 'Dessert',
      materials: [
        '1 ½ cups quick-cooking oats ',
        '¾ cup brown sugar ',
        '¾ cup flax seed meal ',
        '½ cup gluten-free all purpose baking flour ',
        '1 teaspoon baking powder ',
        '½ teaspoon ground cinnamon ',
        '¼ teaspoon salt ',
        '1 banana, mashed ',
        '¼ cup rice milk ',
        '1 egg ',
        '1 teaspoon vanilla extract ',
      ],
      steps: [
        'Preheat oven to 350 degrees F (175 degrees C). Lightly grease an 8x10-inch baking pan.',
        'Mix oats, brown sugar, flax seed meal, flour, baking powder, cinnamon, and salt together in a bowl. Mix banana, rice milk, egg, and vanilla extract together in a separate bowl. Pour banana mixture into flour mixture; stir to combine. Pour batter into the prepared baking pan.',
        'Bake brownies in the preheated oven until a toothpick inserted in the center comes out clean, about 20 minutes. Cover pan with a towel to hold in moisture and cool brownies for at least 5 minutes before serving.',
      ],
      tips: [
        'Per Serving:  129 calories; protein 3.3g; carbohydrates 20.9g; fat 4.1g; cholesterol 15.5mg; sodium 102.1mg. ',
      ],
      imgUrl: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F9044284.jpg',
      metaData: {
        prep: '15 mins ',
        cook: '20 mins ',
        additional: '5 mins ',
        servings: '12 ',
        total: '40 mins ',
        yield: '1 dozen brownies ',
      },
      recipeId: '#5',
      difficulty: 'intermediate',
      publisher: 'Reciper',
    },
    {
      name: 'Creamy Chicken Spaghetti',
      description: 'Great creamy chicken spaghetti dinner kids will love! Garnish with freshly grated Parmesan cheese and serve with a salad and hot garlic bread. ',
      category: 'Spaghetti',
      materials: [
        '1 pound skinless, boneless chicken breasts ',
        '½ teaspoon salt ',
        '½ teaspoon ground black pepper ',
        '1 (16 ounce) package spaghetti ',
        '½ cup salted butter ',
        '1 medium onion, chopped ',
        '1 medium bell pepper, chopped ',
        '1 (10 ounce) can diced tomatoes and green chiles (such as RO*TEL®) ',
        '1 (10.5 ounce) can condensed cream of chicken soup ',
        '1 (10.5 ounce) can condensed cream of mushroom soup ',
        '1 (1 pound) package shredded Mexican cheese blend ',
        ' salt and ground black pepper to taste ',
      ],
      steps: [
        'Bring a large pot of water to a boil. Add chicken, 1/2 teaspoon salt, and 1/2 teaspoon pepper. Cover, reduce heat to a gentle boil, and cook until chicken is no longer pink in the center and the juices run clear, 10 to 12 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C). Remove chicken and set aside until cool enough to handle, then chop into bite-sized pieces. Leave broth in the pot.',
        'Bring broth back to a boil. Cook spaghetti in the boiling broth, stirring occasionally, until tender yet firm to the bite, about 12 minutes. Drain spaghetti; do not rinse. Discard broth.',
        'Melt butter in the same pot. Add onion and bell pepper; saute until softened, 5 to 7 minutes. Add diced tomatoes and chiles, condensed chicken soup, condensed mushroom soup, chicken, and spaghetti, one ingredient at a time, gently mixing after each addition.',
        'Add Cheddar cheese and stir together, mixing well. Season with salt and pepper to taste. Heat until cheese is thoroughly melted, stirring occasionally to keep from scorching.',
      ],
      tips: [
        'Per Serving:  666 calories; protein 33.3g; carbohydrates 52.2g; fat 36.2g; cholesterol 117.7mg; sodium 1320.1mg. ',
      ],
      imgUrl: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F9411232.jpg',
      metaData: {
        prep: '10 mins ',
        cook: '50 mins ',
        additional: '1Hr5Min',
        servings: '8 ',
        total: '1 hr ',
        yield: '8 servings ',
      },
      recipeId: '#30',
      difficulty: 'intermediate',
      publisher: 'Reciper',
    },
  ],
  topCategories: [
    {
      name: 'Dessert',
      number: 10,
      imgUrl: 'https://user-images.githubusercontent.com/78824988/188801418-75c4bba4-53cf-4c38-b56d-e3a75dd4f17a.jpeg',
    },
    {
      name: 'Goat',
      number: 2,
      imgUrl: 'https://user-images.githubusercontent.com/78824988/188802023-2ae10293-acb7-462d-8e78-a012f7e7b02d.jpeg',
    },
    {
      name: 'Chicken',
      number: 11,
      imgUrl: 'https://user-images.githubusercontent.com/78824988/188802183-0c489014-2b08-46ec-b931-81d96612d6e1.jpeg',
    },
    {
      name: 'Beef',
      number: 6,
      imgUrl: 'https://user-images.githubusercontent.com/78824988/188802296-72272c00-8152-4a8b-9f82-c34782076f0d.jpeg',
    },
    {
      name: 'Pork',
      number: 3,
      imgUrl: 'https://user-images.githubusercontent.com/78824988/188802081-8a2a9b2d-e49d-41d1-b15d-4410edf422f4.jpeg',
    },
  ],
};
