export default {
  '#1': {
    name: 'Meatballs',
    description: 'I never knew how to make good meatballs until I found this recipe. I normally make mine with just ground beef and they still taste great. I`ve used the combination of pork, beef and veal and they are equally good. Definitely use fresh bread crumbs and freshly grate your cheese instead of using the canned variety...it really does make a difference. ',
    category: 'Beef',
    materials: [
      '1 pound ground beef ',
      '½ pound ground veal ',
      '½ pound ground pork ',
      '2 cloves garlic, minced ',
      '2 eggs ',
      '1 cup freshly grated Romano cheese ',
      '1 ½ tablespoons chopped Italian flat leaf parsley ',
      'salt and ground black pepper to taste ',
      '2 cups stale Italian bread, crumbled ',
      '1 ½ cups lukewarm water ',
      '1 cup olive oil ',
    ],
    steps: [
      'Combine beef, veal, and pork in a large bowl. Add garlic, eggs, cheese, parsley, salt and pepper.',
      'Blend bread crumbs into meat mixture. Slowly add the water 1/2 cup at a time. The mixture should be very moist but still hold its shape if rolled into meatballs. (I usually use about 1 1/4 cups of water). Shape into meatballs.',
      'Heat olive oil in a large skillet. Fry meatballs in batches. When the meatball is very brown and slightly crisp remove from the heat and drain on a paper towel. (If your mixture is too wet, cover the meatballs while they are cooking so that they hold their shape better.)',
    ],
    tips: [
      'Per Serving:613 calories; protein 26.6g; carbohydrates 6.6g; fat 53.2g; cholesterol 148.6mg; sodium 333.1mg',
    ],
    imgUrl: 'https://user-images.githubusercontent.com/78824988/188808161-65a2743b-45a7-4c05-a34b-efb88126725f.jpeg',
    recipeId: '#1',
    metaData: {
      prep: '30Min',
      cook: '20Min',
      servings: '8',
    },
    difficulty: 'intermediate',
    publisher: 'Reciper',
  },
  '#2': {
    name: 'Meatloaf',
    description: 'This is a very easy and no fail recipe for meatloaf. It won`t take long to make at all, and it`s quite good! ',
    category: 'Beef',
    materials: [
      '1 ½ pounds ground beef ',
      '1 egg ',
      '1 onion, chopped ',
      '1 cup milk ',
      '1 cup dried bread crumbs ',
      'salt and pepper to taste ',
      '2 tablespoons brown sugar ',
      '2 tablespoons prepared mustard ',
      '⅓ cup ketchup ',
    ],
    steps: [
      'Preheat oven to 350 degrees F (175 degrees C).',
      'In a large bowl, combine the beef, egg, onion, milk and bread OR cracker crumbs. Season with salt and pepper to taste and place in a lightly greased 9x5-inch loaf pan, or form into a loaf and place in a lightly greased 9x13-inch baking dish.',
      'In a separate small bowl, combine the brown sugar, mustard and ketchup. Mix well and pour over the meatloaf.',
      'Bake at 350 degrees F (175 degrees C) for 1 hour.',
    ],
    tips: [
      'Per Serving: 372 calories; protein 18.2g; carbohydrates 18.5g; fat 24.7g; cholesterol 98mg; sodium 334.6mg.',
    ],
    imgUrl: 'https://user-images.githubusercontent.com/78824988/188809644-6e1e2de7-bff1-43ba-8a4f-fd7fcf9a7a69.jpeg',
    recipeId: '#2',
    metaData: {
      prep: '15Min',
      cook: '1Hr',
      servings: '8',
    },
    difficulty: 'intermediate',
    publisher: 'Reciper',
  },
  '#15': {
    name: 'Quick Chili',
    description: "Make quick chili with this easy bean chili recipe that can be as mild or spicy as desired. It's even better the next day. ",
    category: 'Beef',
    materials: [
      '2 pounds ground beef ',
      '1 onion, finely diced ',
      '3 cloves garlic, minced ',
      '2 (14.5 ounce) cans diced tomatoes with green chile peppers ',
      '1 (15 ounce) can kidney beans ',
      '1 (15 ounce) can pinto beans ',
      '1 (14.5 ounce) can diced tomatoes ',
      '1 (8 ounce) can tomato sauce ',
      '1 cup water ',
      '2 tablespoons chili powder ',
      '2 tablespoons white sugar ',
      '1 tablespoon hot pepper sauce ',
      '1 tablespoon ground cumin ',
      '1 tablespoon salt ',
      '1 teaspoon ground black pepper ',
    ],
    steps: [
      'Heat a large stockpot over medium-high heat. Cook and stir ground beef in the hot pot until browned and crumbly, 5 to 7 minutes. Drain and discard grease.',
      'Add onion and garlic to beef and cook until onion is translucent, 3 to 4 minutes.',
      'Stir in diced tomatoes with chile peppers, kidney beans, pinto beans, tomatoes, tomato sauce, water, chili powder, sugar, hot pepper sauce, cumin, salt, and pepper. Bring to a boil, reduce heat, and simmer for 30 minutes.',
    ],
    tips: [
      'Per Serving:  489 calories; protein 25.6g; carbohydrates 26.9g; fat 31.3g; cholesterol 96.5mg; sodium 1909.4mg. ',
    ],
    imgUrl: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2020%2F04%2F10%2F870042_quick-chili-i_rock-lobster.jpg',
    metaData: {
      prep: '10 mins ',
      cook: '40 mins ',
      additional: '1Hr5Min',
      servings: '8 ',
      total: '50 mins ',
    },
    recipeId: '#15',
    difficulty: 'intermediate',
    publisher: 'Reciper',
  },
  '#16': {
    name: 'Easy Homemade Chili',
    description: 'Easy homemade chili. Goes great with cornbread or over corn chips for a chili pie! I like to use spicy pinto beans. ',
    category: 'Beef',
    materials: [
      '1 pound ground beef ',
      '1 onion, chopped ',
      '1 (14.5 ounce) can stewed tomatoes ',
      '1 (15 ounce) can tomato sauce ',
      '1 (15 ounce) can kidney beans ',
      '1 ½ cups water ',
      '1 pinch chili powder ',
      '1 pinch garlic powder ',
      ' salt and pepper to taste ',
    ],
    steps: [
      'In a large saucepan over medium heat, combine the beef and onion and saute until meat is browned and onion is tender. Add the stewed tomatoes with juice, tomato sauce, beans and water.',
      'Season with the chili powder, garlic powder, salt and ground black pepper to taste. Bring to a boil, reduce heat to low, cover and let simmer for 15 minutes.',
    ],
    tips: [
      'Per Serving:  394 calories; protein 30.6g; carbohydrates 48.8g; fat 9.2g; cholesterol 45.9mg; sodium 525.6mg. ',
    ],
    imgUrl: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F04%2F26%2F16248_easy-homemade-chili_Rita-1x1-1.jpg',
    metaData: {
      prep: '10 mins ',
      cook: '20 mins ',
      additional: '1Hr5Min',
      servings: '6 ',
      total: '30 mins ',
      yield: '6 servings ',
    },
    recipeId: '#16',
    difficulty: 'intermediate',
    publisher: 'Reciper',
  },
  '#17': {
    name: 'Best Damn Chili',
    description: 'This is my best chili recipe. After years of adjusting recipes that were either too spicy or too mild, everyone loves this. Even my finance who hates chili. ',
    category: 'Beef',
    materials: [
      '4 tablespoons olive oil ',
      '1 yellow onion, chopped ',
      '1 red bell pepper, chopped ',
      '1 Anaheim chile pepper, chopped ',
      '2 red jalapeno pepper, chopped ',
      '4 garlic cloves, minced ',
      '2 ½ pounds lean ground beef ',
      '¼ cup Worcestershire sauce ',
      '1 pinch garlic powder, or to taste ',
      '2 beef bouillon cubes ',
      '1 (12 fluid ounce) can or bottle light beer (such as Coors®) ',
      '1 (28 ounce) can crushed San Marzano tomatoes ',
      '1 (14.5 ounce) can fire-roasted diced tomatoes ',
      '1 (12 ounce) can tomato paste ',
      '½ cup white wine ',
      '2 tablespoons chili powder ',
      '2 tablespoons ground cumin ',
      '1 tablespoon brown sugar ',
      '1 tablespoon chipotle pepper sauce ',
      '2 ½ teaspoons dried basil ',
      '1 ½ teaspoons smoked paprika ',
      '1 teaspoon salt ',
      '½ teaspoon dried oregano ',
      '½ teaspoon ground black pepper ',
      "2 (16 ounce) cans dark red kidney beans (such as Bush's®) ",
      '1 cup sour cream ',
      '3 tablespoons chopped fresh cilantro ',
      '½ teaspoon ground cumin ',
    ],
    steps: [
      'Heat oil in a large pot over medium heat; cook and stir onion, bell pepper, Anaheim pepper, jalapeno peppers, and garlic in the hot oil until softened.',
      'Meanwhile, heat a large skillet over medium-high heat. Cook and stir beef in the hot skillet until browned and crumbly, 5 to 7 minutes; add Worcestershire sauce and garlic powder. Crumble bouillon cubes over beef and add beer. Continue to cook , scraping any browned bits from the bottom of the skillet, until liquid is hot, about 3 minutes. Stir beef mixture into pepper mixture.',
      'Stir crushed tomatoes, diced tomatoes, tomato paste, and wine to the beef mixture. Season with chili powder, 2 tablespoons cumin, brown sugar, pepper sauce, basil, paprika, salt, oregano, and black pepper. Bring to a boil and reduce heat to medium-low. Cover and simmer until meat and vegetables are very tender and flavors have developed in the chili, about 90 minutes, stirring occasionally.',
      'Mix kidney beans into beef and vegetables. Continue to simmer until beans are hot, about 30 minutes more.',
      'Blend sour cream, cilantro, and remaining 1/2 teaspoon cumin in a food processor until smooth. Serve sour cream mixture with chili.',
    ],
    tips: [
      'Per Serving:  406 calories; protein 25.2g; carbohydrates 27.6g; fat 21.1g; cholesterol 74.4mg; sodium 1014.5mg. ',
    ],
    imgUrl: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F04%2F06%2F233613-Best-Damn-Chili-mfs-242-2.jpg',
    metaData: {
      prep: '30 mins ',
      cook: '2 hrs 15 mins ',
      additional: '1Hr5Min',
      servings: '12 ',
      total: '2 hrs 45 mins ',
      yield: '12 servings ',
    },
    recipeId: '#17',
    difficulty: 'intermediate',
    publisher: 'Reciper',
  },
  '#18': {
    name: 'Mini Meatloaves',
    description: "This mini meatloaf recipe is quick and easy to make. It's a family favorite. The ketchup and brown sugar give these loaves a tangy flavor. ",
    category: 'Beef',
    materials: [
      '1 cup shredded Cheddar cheese ',
      '¾ cup milk ',
      '½ cup quick cooking oats ',
      '1 large egg ',
      '1 teaspoon salt ',
      '1 pound ground beef ',
      '⅔ cup ketchup ',
      '¼ cup packed brown sugar ',
      '1 ½ teaspoons prepared mustard ',
    ],
    steps: [
      'Preheat the oven to 350 degrees F (175 degrees C). Lightly grease a 9x13-inch baking dish.',
      'Stir together cheese, milk, oats, egg, and salt in a large bowl. Mix in ground beef until well combined. Form mixture into 8 mini meatloaves; place in the prepared baking dish.',
      'Combine ketchup, brown sugar, and mustard in a small bowl; stir well. Spread over each meatloaf.',
      'Bake uncovered for 45 minutes. An instant-read thermometer inserted into the center should read at least 160 degrees F (72 degrees C).',
    ],
    tips: [
      'Per Serving:  255 calories; protein 15.1g; carbohydrates 16.6g; fat 14.4g; cholesterol 73.9mg; sodium 656mg. ',
    ],
    imgUrl: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4549680.jpg',
    metaData: {
      prep: '15 mins ',
      cook: '45 mins ',
      additional: '1Hr5Min',
      servings: '8 ',
      total: '1 hr ',
    },
    recipeId: '#18',
    difficulty: 'intermediate',
    publisher: 'Reciper',
  },
};
